[package]
name = "keyrocky"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.24"
thiserror = "1.0.35"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "io-std", "macros"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
tungstenite = "0.17.3"
